version: "3.9"

networks:
  siberiana-network:
    name: siberiana-network
    external: true

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    container_name: client
    restart: always
    environment:
     NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
     NEXTAUTH_URL: ${NEXTAUTH_URL}
     NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
     OIDC_ISSUER: ${OIDC_ISSUER}
     OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
     OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
     NEXT_PUBLIC_STRAPI_API_URL: ${NEXT_PUBLIC_STRAPI_API_URL}
     NEXT_PUBLIC_STRAPI_DOMAIN: ${NEXT_PUBLIC_STRAPI_DOMAIN}
     NEXT_PUBLIC_SIBERIANA_API_URL: ${NEXT_PUBLIC_SIBERIANA_API_URL}
     NEXT_PUBLIC_S3_DOMAIN: ${NEXT_PUBLIC_S3_DOMAIN}
     REVALIDATE_TOKEN: ${REVALIDATE_TOKEN}
    ports:
      - 3000:3000
    networks:
      - siberiana-network
